In [6]:
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np
from folium.features import GeoJson, GeoJsonTooltip, GeoJsonPopup
from folium.plugins import TimeSliderChoropleth
import folium
import seaborn as sns
import os
from branca.colormap import linear
from pandas.io.json import json_normalize
from LocalFunctions import get_hex_colors

%matplotlib inline

In [15]:
df1 = pd.read_json('https://api.covid19india.org/raw_data1.json')
df2 = pd.read_json('https://api.covid19india.org/raw_data2.json')
df3 = pd.read_json('https://api.covid19india.org/raw_data3.json')

In [16]:
dfj1 = json_normalize(df1['raw_data'])
dfj2 = json_normalize(df2['raw_data'])
dfj3 = json_normalize(df3['raw_data'])

In [19]:
dfj3.columns

Index(['agebracket', 'contractedfromwhichpatientsuspected', 'currentstatus',
       'dateannounced', 'detectedcity', 'detecteddistrict', 'detectedstate',
       'entryid', 'gender', 'nationality', 'notes', 'numcases', 'source1',
       'source2', 'source3', 'statecode', 'statepatientnumber',
       'statuschangedate', 'typeoftransmission'],
      dtype='object')

In [32]:
df = pd.DataFrame()

In [33]:
df = df.append(dfj1)
df = df.append(dfj2)
df = df.append(dfj3)

C:\Users\kisha\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [37]:
df

,agebracket,backupnotes,contractedfromwhichpatientsuspected,currentstatus,dateannounced,detectedcity,detecteddistrict,detectedstate,entryid,estimatedonsetdate,...,notes,numcases,patientnumber,source1,source2,source3,statecode,statepatientnumber,statuschangedate,typeoftransmission
0,20,Student from Wuhan,,Recovered,30/01/2020,Thrissur,Thrissur,Kerala,NaN,,...,Travelled from Wuhan,NaN,1,https://twitter.com/vijayanpinarayi/status/122...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-TS-P1,14/02/2020,Imported
1,,Student from Wuhan,,Recovered,02/02/2020,Alappuzha,Alappuzha,Kerala,NaN,,...,Travelled from Wuhan,NaN,2,https://www.indiatoday.in/india/story/kerala-r...,https://weather.com/en-IN/india/news/news/2020...,,KL,KL-AL-P1,14/02/2020,Imported
2,,Student from Wuhan,,Recovered,03/02/2020,Kasaragod,Kasaragod,Kerala,NaN,,...,Travelled from Wuhan,NaN,3,https://www.indiatoday.in/india/story/kerala-n...,https://twitter.com/ANI/status/122422148580539...,https://weather.com/en-IN/india/news/news/2020...,KL,KL-KS-P1,14/02/2020,Imported
3,45,Travel history to Italy and Austria,,Recovered,02/03/2020,East Delhi (Mayur Vihar),East Delhi,Delhi,NaN,,...,"Travelled from Austria, Italy",NaN,4,https://www.indiatoday.in/india/story/not-a-ja...,https://economictimes.indiatimes.com/news/poli...,,DL,DL-P1,15/03/2020,Imported
4,24,"Travel history to Dubai, Singapore contact",,Recovered,02/03/2020,Hyderabad,Hyderabad,Telangana,NaN,,...,"Travelled from Dubai to Bangalore on 20th Feb,...",NaN,5,https://www.deccanherald.com/national/south/qu...,https://www.indiatoday.in/india/story/coronavi...,https://www.thehindu.com/news/national/coronav...,TG,TS-P1,02/03/2020,Imported
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,,NaN,,,,,,,2774,NaN,...,,,NaN,,,,,,,
2774,,NaN,,,,,,,2775,NaN,...,,,NaN,,,,,,,
2775,,NaN,,,,,,,2776,NaN,...,,,NaN,,,,,,,
2776,,NaN,,,,,,,2777,NaN,...,,,NaN,,,,,,,
2777,,NaN,,,,,,,2778,NaN,...,,,NaN,,,,,,,